baseurl: https://UselessCalculations.com/
languageCode: en-us
title: Useless Calculations
theme: uselesscalc

# frontmatter:
#   date: "lastmod"

# enableGitInfo: true
enableRobotsTXT: true
metaDataFormat: yaml

paginate: 10
paginatePath: page

# disqusShortname: your_disqus_shortname
permalinks:
  posts: '/:year/:month/:slug/'
  code: '/:slug/'
taxonomies:
  tag: tags
  topic: topics

summaryLength: 30
enableEmoji: true
pygmentsCodeFences: true

# disqusShortname: "" #Disqus shortname
googleAnalytics: UA-120239279-1

author:
  name: Adam Haile
  github: adammhaile/UselessCalculations
  twitter: UselessCalc
# params:
#   tagline: Completely useless mathematical calculations for which I only asked if I could, not if I should.


privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: false
  speakerDeck:
    disable: true
  twitter:
    disable: false
    enableDNT: false
  vimeo:
    disable: false
  youtube:
    disable: false
    privacyEnhanced: true